version: '3.1.1'



services:
  vault:
    image: hashicorp/vault
    container_name: vault
    cap_add:
      - IPC_LOCK
    environment:
      "VAULT_DEV_ROOT_TOKEN_ID": aabbcc
      "VAULT_DEV_LISTEN_ADDRESS": 0.0.0.0:1234
    volumes:
      - ./vault:/vault/config.d
